apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: rabbitmq-server
type: Opaque
data:
  rabbitmq-erlang-cookie: "xxxxxxxxxxxxxxxxxxxxxxx"
  rabbitmq-password: "xxxxxxxxxxxx"
